Repository blockful-io/swaplace-dapp, pull requests merged in 2024-03, with the labels that each got.

#193 Feat/style station
  components/01-atoms/ApprovedTokenCards.tsx
  components/01-atoms/ENSAvatar.tsx
  components/01-atoms/NetworkDropdown.tsx
  components/01-atoms/SwapExpireTime.tsx
  components/01-atoms/SwapModalButton.tsx
  components/01-atoms/icons/ArrowIcon.tsx
  components/01-atoms/icons/CloseCTA.tsx
  components/01-atoms/icons/LeftIcon.tsx
  components/01-atoms/icons/RightIcon.tsx
  components/01-atoms/index.ts
  components/02-molecules/CardOffers.tsx
  components/02-molecules/OfferSummary.tsx
  components/02-molecules/TokenCard.tsx
  components/02-molecules/TokensList.tsx
  components/02-molecules/UserOfferInfo.tsx
  components/03-organisms/ApproveTokenCard.tsx
  components/03-organisms/SwapStation.tsx
  components/03-organisms/TokenOffers.tsx
Labels: enhancement

#206 fix light mode label
  components/02-molecules/TokenCard.tsx
Labels: bug

#226 fix: grid not showing in swap confirmation modal
  components/01-atoms/SwapModalLayout.tsx
  components/01-atoms/TokenCardsPlaceholder.tsx
  components/02-molecules/CardOffers.tsx
  components/02-molecules/OfferSummary.tsx
  components/02-molecules/TokensList.tsx
Labels: bug, enhancement

#257 feat: erc20 allowance
  components/02-molecules/ConfirmSwapModal.tsx
  components/02-molecules/TokenAmountSelectionModal.tsx
  components/02-molecules/TokenCard.tsx
  components/02-molecules/TokensList.tsx
  components/03-organisms/ApproveTokenCard.tsx
  lib/client/blockchain-utils.ts
  lib/client/ui-utils.ts
  lib/service/verifyTokensSwapApproval.ts
  lib/shared/types.ts
  lib/wallet/wallet-config.ts
  package-lock.json
Labels: enhancement
