Repository blockful-io/swaplace-dapp, pull requests merged in 2024-02, with the labels that each got.

#103 feat: ENSAvatar component
  .env.example
  .eslintrc
  .github/workflows/eslint.yml
  README.md
  components/01-atoms/ConnectWallet.tsx
  components/01-atoms/ENSAvatar.tsx
  components/01-atoms/EmptyNftsCards.tsx
  components/01-atoms/SearchBar.tsx
  components/01-atoms/SelectDestinyChain.tsx
  components/01-atoms/SwappingIcons.tsx
  components/01-atoms/icons/SelectUserIcon.tsx
  components/01-atoms/index.ts
  components/02-molecules/CardHome.tsx
  components/02-molecules/NftCard.tsx
  components/02-molecules/NftsList.tsx
  components/02-molecules/SwapStation.tsx
  components/02-molecules/TheHeader.tsx
  components/03-organisms/NftsShelf.tsx
  components/04-templates/Layout.tsx
  lib/client/blockchain-data.ts
  lib/client/constants.ts
  lib/client/hooks/subgraphQueries.ts
  lib/client/hooks/useENSData.tsx
  lib/client/utils.ts
  package-lock.json
  package.json
  pages/index.tsx
  pages/offers.tsx
  pages/swap.tsx
  styles/global.css
  tailwind.config.ts
Labels: enhancement

#144 docs: cleared instructions on README.md
  README.md
Labels: documentation

#148 feat: add TokensOfferSkeleton
  components/01-atoms/TokensOfferSkeleton.tsx
Labels: enhancement

#150 feat: add three dots card offers options
  components/01-atoms/ThreeDotsCardOffersOptions.tsx
  components/01-atoms/icons/CheckIcon.tsx
  components/01-atoms/icons/DoneIcon.tsx
  components/01-atoms/icons/ShareIcon.tsx
  components/01-atoms/icons/ThreeDotsIcon.tsx
  components/01-atoms/index.ts
Labels: enhancement

#151 feat: add swap-offer details component
  components/01-atoms/SwapOfferDetails.tsx
Labels: enhancement

#154 Feat/card offers
  components/01-atoms/TokenOfferDetails.tsx
  components/01-atoms/TokensOfferSkeleton.tsx
  components/01-atoms/index.ts
  components/02-molecules/CardOffers.tsx
  components/02-molecules/index.tsx
  components/03-organisms/SwapStation.tsx
  components/03-organisms/index.tsx
  components/04-templates/SwapSection.tsx
Labels: enhancement

#155 Feat/token offers
  components/01-atoms/icons/SwapIcon.tsx
  components/03-organisms/TokenOffers.tsx
  components/03-organisms/index.tsx
  components/04-templates/OfferSection.tsx
Labels: enhancement

#167 feat: token offer variant
  components/01-atoms/NftsCardApprovedList.tsx
  components/01-atoms/SwapModalLayout.tsx
  components/01-atoms/icons/SwapIcon.tsx
  components/02-molecules/CardOffers.tsx
  components/02-molecules/ConfirmSwapModal.tsx
  components/02-molecules/OfferSummary.tsx
  components/02-molecules/UserOfferInfo.tsx
  components/03-organisms/NftsShelf.tsx
  components/03-organisms/TokenOffers.tsx
  styles/global.css
Labels: enhancement

#173 fix: alignment of address in walletSidebarTemplate
  components/02-molecules/EnsNameAndAddressWallet.tsx
Labels: bug
